import { GoogleGenerativeAI, Part } from '@google/generative-ai';

const GEMINI_API_KEY = process.env.GEMINI_API_KEY!;

if (!GEMINI_API_KEY) {
  throw new Error('GEMINI_API_KEY is not set');
}

const genAI = new GoogleGenerativeAI(GEMINI_API_KEY);

const TEXT_MODEL = process.env.GEMINI_MODEL || 'gemini-2.5-flash-preview-05-20';
const IMAGE_MODEL = process.env.GEMINI_IMAGE_MODEL || 'gemini-2.5-flash-preview-05-20';

const MODELS = [TEXT_MODEL];

async function tryWithFallback(
  fn: (modelName: string) => Promise<string>
): Promise<string> {
  for (const modelName of MODELS) {
    try {
      return await fn(modelName);
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err);
      console.warn(`Model ${modelName} failed: ${message}`);
      continue;
    }
  }
  throw new Error('All Gemini models failed');
}

export async function generateText(prompt: string, systemInstruction?: string): Promise<string> {
  return tryWithFallback(async (modelName) => {
    const model = genAI.getGenerativeModel({
      model: modelName,
      ...(systemInstruction && { systemInstruction }),
    });
    const result = await model.generateContent(prompt);
    return result.response.text();
  });
}

export async function generateVisionContent(
  prompt: string,
  imageBase64: string,
  mimeType: string = 'image/jpeg',
  systemInstruction?: string
): Promise<string> {
  const model = genAI.getGenerativeModel({
    model: IMAGE_MODEL,
    ...(systemInstruction && { systemInstruction }),
  });
  const imagePart: Part = {
    inlineData: { data: imageBase64, mimeType },
  };
  const result = await model.generateContent([prompt, imagePart]);
  return result.response.text();
}

export async function generateChat(
  history: Array<{ role: string; parts: Array<{ text: string }> }>,
  message: string,
  systemInstruction?: string
): Promise<string> {
  return tryWithFallback(async (modelName) => {
    const model = genAI.getGenerativeModel({
      model: modelName,
      ...(systemInstruction && { systemInstruction }),
    });
    const chat = model.startChat({
      history: history.map((h) => ({
        role: h.role as 'user' | 'model',
        parts: h.parts,
      })),
    });
    const result = await chat.sendMessage(message);
    return result.response.text();
  });
}

export async function generateJSON<T>(prompt: string, systemInstruction?: string): Promise<T> {
  const text = await generateText(prompt, systemInstruction);
  const cleaned = text.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim();
  return JSON.parse(cleaned) as T;
}

export async function generateImage(
  prompt: string,
  systemInstruction?: string
): Promise<{ imageBase64: string; mimeType: string; text?: string }> {
  const imageModel = process.env.GEMINI_IMAGE_MODEL || 'gemini-3-pro-image-preview';
  const model = genAI.getGenerativeModel({
    model: imageModel,
    ...(systemInstruction && { systemInstruction }),
    generationConfig: {
      // @ts-expect-error - responseModalities is supported by image models
      responseModalities: ['TEXT', 'IMAGE'],
    },
  });

  const result = await model.generateContent(prompt);
  const response = result.response;
  const candidates = response.candidates;

  if (!candidates || candidates.length === 0) {
    throw new Error('No response from image model');
  }

  let imageBase64 = '';
  let mimeType = 'image/png';
  let text = '';

  for (const part of candidates[0].content.parts) {
    if (part.inlineData) {
      imageBase64 = part.inlineData.data;
      mimeType = part.inlineData.mimeType || 'image/png';
    } else if (part.text) {
      text = part.text;
    }
  }

  if (!imageBase64) {
    throw new Error('No image generated by model');
  }

  return { imageBase64, mimeType, text };
}

export { genAI };
